backend:
  name: git-gateway
  branch: main   # or master, depending on your repo

media_folder: "uploads"   # Folder where uploaded images will be stored in repo
public_folder: "/uploads" # Public URL for uploaded media

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
